name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
          cache: true
          cache-key: 'flutter-3.29.3'
          cache-path: ${{ runner.tool_cache }}/flutter

      - run: flutter pub get

      - run: flutter analyze --no-fatal-infos

      - run: flutter test

      - run: flutter build apk --debug

      - uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7